// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/akaimo/sample-controller/pkg/client/clientset/versioned/typed/samplecontroller/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeExampleV1 struct {
	*testing.Fake
}

func (c *FakeExampleV1) SampleResources(namespace string) v1.SampleResourceInterface {
	return &FakeSampleResources{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeExampleV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
