apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sample-controller.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "sample-controller.name" . }}
    helm.sh/chart: {{ template "sample-controller.chart" . }}
