// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/akaimo/sample-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SampleResources returns a SampleResourceInformer.
	SampleResources() SampleResourceInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SampleResources returns a SampleResourceInformer.
func (v *version) SampleResources() SampleResourceInformer {
	return &sampleResourceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
