// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	samplecontrollerv1 "github.com/akaimo/sample-controller/pkg/apis/samplecontroller/v1"
	versioned "github.com/akaimo/sample-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/akaimo/sample-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/akaimo/sample-controller/pkg/client/listers/samplecontroller/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SampleResourceInformer provides access to a shared informer and lister for
// SampleResources.
type SampleResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SampleResourceLister
}

type sampleResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSampleResourceInformer constructs a new informer for SampleResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSampleResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSampleResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSampleResourceInformer constructs a new informer for SampleResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSampleResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecontrollerV1().SampleResources(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecontrollerV1().SampleResources(namespace).Watch(options)
			},
		},
		&samplecontrollerv1.SampleResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *sampleResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSampleResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sampleResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&samplecontrollerv1.SampleResource{}, f.defaultInformer)
}

func (f *sampleResourceInformer) Lister() v1.SampleResourceLister {
	return v1.NewSampleResourceLister(f.Informer().GetIndexer())
}
