apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: sample-controller
rules:
  - apiGroups:
      - "samplecontroller.k8s.io"
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "list"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sample-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sample-controller
subjects:
  - kind: ServiceAccount
    name: sample-controller
    namespace: default