// Code generated by lister-gen. DO NOT EDIT.

package v1

// SampleResourceListerExpansion allows custom methods to be added to
// SampleResourceLister.
type SampleResourceListerExpansion interface{}

// SampleResourceNamespaceListerExpansion allows custom methods to be added to
// SampleResourceNamespaceLister.
type SampleResourceNamespaceListerExpansion interface{}
