apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sampleresources.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: sampleresources
    singular: sampleresource
    kind: SampleResource
    shortNames:
      - smp
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: message
      type: string
      description: message content which want to show
      JSONPath: .status.message
    - name: AGE
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          properties:
            time:
              type: string
          required:
            - time
